development:
  adapter: postgresql
  encoding: unicode
  database: housefoldr_development
  pool: 5
  username: Kevin
  password: 98bnsrgk

test:
  adapter: postgresql
  encoding: unicode
  database: housefoldr_test
  pool: 5
  username: Kevin
  password: 98bnsrgk