development:
  adapter: postgresql
  encoding: unicode
  database: housefoldr_development
  pool: 5
  username: wynnemlo
  password: candy123

test:
  adapter: postgresql
  encoding: unicode
  database: housefoldr_test
  pool: 5
  username: wynnemlo
  password: candy123